# Generated by Django 4.0.2 on 2022-02-21 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.IntegerField(unique=True)),
                ('date_of_purchase', models.DateField()),
                ('customer_id', models.IntegerField()),
                ('fuel', models.CharField(max_length=20)),
                ('vehicle_segment', models.CharField(max_length=10)),
                ('premium', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1)])),
                ('bodily_injury_liability', models.BooleanField(default=False)),
                ('personal_injury_protection', models.BooleanField(default=False)),
                ('property_damage_liability', models.BooleanField(default=False)),
                ('collision', models.BooleanField(default=False)),
                ('comprehensive', models.BooleanField(default=False)),
                ('customer_gender', models.CharField(max_length=10)),
                ('customer_income_group', models.CharField(max_length=10)),
                ('customer_region', models.CharField(max_length=20)),
                ('customer_marital_status', models.BooleanField(default=False)),
            ],
        ),
    ]
